server:
  port: $SERVER_PORT
firebase:
  enabled: false
database:
  host: dezzles-apps-do-user-35978446-0.h.db.ondigitalocean.com
  port: 25060
  username: ribbon-quest-prod
  password: $DATABASE_PASSWORD_PROD
  database: ribbon-quest-prod
  prod: true
app:
  jwtSecret: $JWT_SECRET_PROD