name: Build And Deploy Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - uses: dezzles-apps/action-event/actions/event@main
        with:
          credentialsJson: ${{ secrets.GCLOUD_KEY_FILE }}
          message: "Starting build process for commit: ${{ github.event.head_commit.url }}"

  configuration:
    uses: dezzles-apps/actions/.github/workflows/create-config.yml@main
    needs: [ notify-start ]
    
  build-ui:
    uses: dezzles-apps/actions/.github/workflows/build-docker.yml@main
    needs: [ configuration, notify-start ]
    with:
      app-name: rq-ui
      docker-context: ./rq-ui
      version: '${{ needs.configuration.outputs.version }}'
    secrets: inherit

  build-api:
    uses: dezzles-apps/actions/.github/workflows/build-docker.yml@main
    needs: [ configuration, notify-start ]
    with:
      app-name: rq-server
      docker-context: ./rq-server
      version: '${{ needs.configuration.outputs.version }}'
    secrets: inherit

  generate-specs:
    uses: dezzles-apps/actions/.github/workflows/create-specs.yml@main
    needs: [ configuration ]
    with:
      version: '${{ needs.configuration.outputs.version }}'
      spec: project.yml
    secrets: inherit

  deploy-non:
    uses: dezzles-apps/actions/.github/workflows/cloud-run-spec-deploy.yml@main
    needs: [ generate-specs, build-ui, build-api]
    with:
      environment: non
      app-name: ribbon-quest
    secrets: inherit

  deploy-prod:
    uses: dezzles-apps/actions/.github/workflows/cloud-run-spec-deploy.yml@main
    needs: [ deploy-non ]
    if: 
    with:
      environment: prod
      app-name: ribbon-quest
    secrets: inherit

  publish:
    uses: dezzles-apps/actions/.github/workflows/publish-to-portfolio.yml@main
    needs: [ deploy-prod, deploy-non, configuration ]
    with:
      version: '${{ needs.configuration.outputs.version }}'
    secrets: inherit

  notify-end:
    name: Post a message in a channel
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - uses: dezzles-apps/action-event/actions/event@main
        with:
          credentialsJson: ${{ secrets.GCLOUD_KEY_FILE }}
          message: "Build process completed for commit: ${{ github.event.head_commit.url }}"
